Hw4
waniak7/Home-work pull request #5
Opened 2018-11-04 09:57 UTC by waniak7

пока что без слайдера, сегодня доделаю его

![hw](https://user-images.githubusercontent.com/38732745/47960206-ce900680-dfff-11e8-88f4-70e8863db233.png)

2018-11-04 13:40 UTC, waniak7 commented
со слайдером
![1](https://user-images.githubusercontent.com/38732745/47964837-e55a4b80-e047-11e8-8129-528eff8a9520.png)

2018-11-04 21:42 UTC, yana-tsylinska requested changes
гарна робота))

2018-11-04 21:42 UTC, yana-tsulya commented on hw4/index.html
> +            <img src="images/logo.png" alt="Театр імені Т. Г. Шевченка" class="logo">
при кліку на лого, користувач завжди повинен мати можливість перейти на головну сторінку, ти тут здається лінку загубив ;)

2018-11-04 21:42 UTC, yana-tsulya commented on hw4/index.html
> +            <a href=""> <!-- empty --></a>
якщо при кліку не має бути ніякого переходу на інші сторінки, краще використати button + гарною практикою є завжди добавляти всередину таких клікабельних елементів якийсь текст для скрін-рідерів))

2018-11-04 21:42 UTC, yana-tsulya commented on hw4/index.html
> +        <li class="active-item-info">
ця інформація має бути частиною активного айтему, в неактивних айтемах вона просто схована)

2018-11-04 21:42 UTC, yana-tsulya commented on hw4/index.html
> +<div class="main-content">
ось цей враппер здається зайвий, ти можеш той самий класс перенести на наступний дів))

2018-11-04 21:42 UTC, yana-tsulya commented on hw4/index.html
> +    </div>
зайвий елемент для 'дизайну', сам бордер можна було через ::before добавити, а лінку позиціонувати відносно твого основного футеру))

2018-11-04 21:42 UTC, yana-tsulya commented on hw4/index.html
> +    </div>
точніше на футеру а div.container всередині футеру))

2018-11-04 21:42 UTC, yana-tsulya commented on hw4/styles/style.css
> +
стилі що йдуть зверху цього коммента, можна поправити/добавити в reset, особливо глобальний фонт - він для зручності завжди добавляється в ресеті, також поправ фонт для лінок))

2018-11-04 21:42 UTC, yana-tsulya commented on hw4/styles/style.css
> +    z-index: 10;
а навіщо тобі тут z-index?

2018-11-05 13:26 UTC, waniak7 commented on hw4/styles/style.css
> +    z-index: 10;
там на макеті видно, що афіша з наступної секції трохи залазить під хедер. тепер розумію що це якось не дуже логічно бо якби було інше фото то якась важливий напис з афіші міг би залізти. приберу це взагалі)

2018-12-02 16:47 UTC, merged